version: '3.9'

services:
  db:
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      influxdb_net:
        ipv4_address: 172.18.0.4
    volumes:
      - type: bind
        source: /home/db/influxdb2
        target: /var/lib/influxdb2
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - influxdb_net
    volumes:
      - /var/run/:/var/run/
      - shared_res:/home/app/webapp/res/
      - influxdb_collector:/home/app/influxdb_collector/
    tty: true
    command: ./manage.py runserver 0.0.0.0:8000
volumes:
  shared_res:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/app/res
  influxdb_collector:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/app/influxdb_collector
networks:
  influxdb_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

